"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { Feature, disclaimer } from "@/lib/demo";

type Config = { feature: Feature; title: string; promise: string; warning: string; endpoint: string; fields: { name: string; label: string; type?: "text" | "textarea" | "select"; required?: boolean; options?: string[] }[] };
export function FeaturePage({ config }: { config: Config }) {
  const [result, setResult] = useState<Record<string, unknown> | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setError(""); setBusy(true); const form = new FormData(e.currentTarget); const body = Object.fromEntries(form); try { const r = await fetch(config.endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const json = await r.json(); if (!r.ok) throw new Error(json.error?.message ?? "Please try again."); setResult(json.data); } catch (e) { setError(e instanceof Error ? e.message : "Please try again."); } finally { setBusy(false); } }
  return <main className="feature-wrap"><Link className="back" href="/">← All guidance</Link><p className="eyebrow">DEMO MODE · NO DATA SAVED</p><h1>{config.title}</h1><p className="lede">{config.promise}</p><aside className="warning"><strong>Before you continue:</strong> {config.warning}</aside>{!result ? <form onSubmit={submit} noValidate><div className="form-grid">{config.fields.map((f) => <label key={f.name}>{f.label}{f.type === "textarea" ? <textarea name={f.name} required={f.required} minLength={f.required ? 10 : undefined} /> : f.type === "select" ? <select name={f.name} required={f.required}><option value="">Choose one</option>{f.options?.map(o => <option key={o} value={o}>{o.replaceAll("_", " ")}</option>)}</select> : <input name={f.name} required={f.required} />}</label>)}</div><button disabled={busy} type="submit">{busy ? "Preparing your guidance…" : "Get guidance"}</button>{error && <p role="alert" className="error">{error}</p>}</form> : <section className="result" aria-live="polite"><p className="eyebrow">DEMO RESULT</p><h2>{String(result.summary ?? result.issueSummary ?? result.urgency ?? "Your guidance")}</h2><Result data={result} /><p className="disclaimer">{String(result.disclaimer ?? disclaimer)}</p><div className="result-actions"><button onClick={() => navigator.clipboard.writeText(document.body.innerText)}>Copy guidance</button><button onClick={() => window.print()}>Print</button><button onClick={() => setResult(null)}>Start over</button></div></section>}<p className="footer-note">{disclaimer}</p></main>;
}
function Result({ data }: { data: Record<string, unknown> }) { const keys = ["todayActions", "immediateActions", "actions", "nextSteps", "sevenDayPlan", "drivers", "missingFacts", "limitations"]; return <>{keys.map(k => Array.isArray(data[k]) && <section key={k}><h3>{k.replace(/([A-Z])/g, " $1")}</h3><ol>{(data[k] as unknown[]).slice(0, 5).map((x, i) => <li key={i}>{String(x)}</li>)}</ol></section>)}{Array.isArray(data.matches) && <section><h3>Possible matches</h3>{(data.matches as { officialName: string; match: string; why: string[] }[]).map(x => <article className="match" key={x.officialName}><strong>{x.officialName}</strong><p>{x.match.replace("_", " ")}</p><p>{x.why.join(" ")}</p></article>)}</section>}</> }
