"use client";

import { useEffect, useRef, useState } from "react";
import type { CrisisType, LifelineAction, LifelineFormData, LifelineResult, LifelineScheme, ScreenState } from "@/types/lifeline";

const CRISIS_TYPES: CrisisType[] = [
  { value: "job_loss", emoji: "01", title: "Lost a job or income", description: "Layoff, salary cut, business loss, or a client stopped paying" },
  { value: "medical_emergency", emoji: "02", title: "Medical emergency", description: "Hospital bills, serious illness, accident, or surgery" },
  { value: "housing_crisis", emoji: "03", title: "Housing or eviction risk", description: "Rent pressure, eviction threat, or an unsafe home" },
  { value: "debt_trap", emoji: "04", title: "Debt or loan pressure", description: "Loan-app harassment, moneylender pressure, or debt spiral" },
  { value: "utility_disconnection", emoji: "05", title: "Utility disconnection", description: "Electricity, water, or gas has been cut or is at risk" },
];

const STATES = ["Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal", "Andaman and Nicobar Islands", "Chandigarh", "Dadra and Nagar Haveli and Daman and Diu", "Jammu and Kashmir", "Ladakh", "Lakshadweep", "Puducherry"];
const CITY_TO_STATE: Record<string, string> = { mumbai: "Maharashtra", pune: "Maharashtra", nagpur: "Maharashtra", nashik: "Maharashtra", delhi: "Delhi", "new delhi": "Delhi", noida: "Uttar Pradesh", gurgaon: "Haryana", gurugram: "Haryana", bangalore: "Karnataka", bengaluru: "Karnataka", mysore: "Karnataka", mysuru: "Karnataka", chennai: "Tamil Nadu", coimbatore: "Tamil Nadu", madurai: "Tamil Nadu", hyderabad: "Telangana", secunderabad: "Telangana", visakhapatnam: "Andhra Pradesh", vizag: "Andhra Pradesh", vijayawada: "Andhra Pradesh", kolkata: "West Bengal", calcutta: "West Bengal", ahmedabad: "Gujarat", surat: "Gujarat", jaipur: "Rajasthan", jodhpur: "Rajasthan", bhopal: "Madhya Pradesh", indore: "Madhya Pradesh", lucknow: "Uttar Pradesh", kanpur: "Uttar Pradesh", varanasi: "Uttar Pradesh", patna: "Bihar", gaya: "Bihar", chandigarh: "Punjab", ludhiana: "Punjab", amritsar: "Punjab", kochi: "Kerala", thiruvananthapuram: "Kerala", trivandrum: "Kerala", bhubaneswar: "Odisha", cuttack: "Odisha", ranchi: "Jharkhand", guwahati: "Assam", raipur: "Chhattisgarh", shimla: "Himachal Pradesh", dehradun: "Uttarakhand", panaji: "Goa" };
const EARNER_TYPES = ["Salaried employee", "Daily wage or informal worker", "Freelancer or self-employed", "Gig worker (delivery, cab, etc.)", "Small business owner", "Student with part-time income", "Homemaker managing household", "Retired or pensioner"];
const EMPTY_FORM: LifelineFormData = { crisisType: "", description: "", monthlyIncome: "", city: "", state: "", familySize: "", earnerType: "" };
const detectState = (city: string) => CITY_TO_STATE[city.trim().toLowerCase()] || "";

function FlowHeader({ step }: { step: 1 | 2 | 3 }) { return <div className="lifeline-flow-header"><div className="lifeline-crumb"><b aria-hidden="true">A</b><span>ANCHOR</span><i>/</i><em>LIFELINE</em></div><div className="lifeline-progress" aria-label={`Step ${step} of 3`}>{[1, 2, 3].map((item) => <span className={item <= step ? "active" : ""} key={item}>{item}</span>)}</div></div>; }
function Actions({ title, subtitle, items, tone }: { title: string; subtitle: string; items: LifelineAction[]; tone: "urgent" | "week" | "month" }) { return <section className={`lifeline-actions ${tone}`}><div className="lifeline-section-heading"><span className="lifeline-section-marker" /><div><h2>{title}</h2><p>{subtitle}</p></div></div><div className="lifeline-action-list">{items.map((item, index) => <article className="lifeline-action" key={`${item.action}-${index}`}><span className="lifeline-action-number">{String(index + 1).padStart(2, "0")}</span><div><strong>{item.action}</strong><p><small>Why this matters</small>{item.why}</p><p className="how"><small>How to start</small>{item.how}</p></div></article>)}</div></section>; }
function SchemeCard({ scheme }: { scheme: LifelineScheme }) { return <article><header><div><small>{scheme.ministry}</small><strong>{scheme.name}</strong></div><b>{scheme.valueDisplay}</b></header><dl><div><dt>What it provides</dt><dd>{scheme.benefit}</dd></div><div><dt>Why it may fit</dt><dd className="eligible">{scheme.eligibility}</dd></div><div><dt>How to apply</dt><dd>{scheme.howToApply}</dd></div></dl><footer><span>Typical access: {scheme.timeToAccess}</span><a href={scheme.applyUrl} target="_blank" rel="noreferrer">View application <span aria-hidden="true">→</span></a></footer></article>; }
function SchemeGroup({ type, stateName, schemes }: { type: "national" | "state"; stateName: string; schemes: LifelineScheme[] }) { const isState = type === "state"; const label = isState ? `${stateName} state schemes` : "National schemes"; return <section className={`lifeline-schemes ${isState ? "state-schemes" : "national-schemes"}`}><div className="lifeline-scheme-title"><div><h2>{label}</h2><p>{isState ? `Programmes run by the ${stateName} government.` : "Programmes funded and run by the Government of India."}</p></div><span>{isState ? `${stateName} government` : "Central government"}</span></div><p className="lifeline-scheme-count">{schemes.length} {schemes.length === 1 ? "programme" : "programmes"} to verify</p>{schemes.length ? schemes.map((scheme) => <SchemeCard key={`${scheme.name}-${scheme.applyUrl}`} scheme={scheme} />) : <article className="lifeline-fallback">{isState ? `State-specific programmes for ${stateName} are being verified. Use the ${stateName} government portal for the latest support.` : "No national programme can be safely suggested from these details. Visit india.gov.in to find official services."}</article>}</section>; }

export default function Lifeline({ initialScreen = "intro" }: { initialScreen?: ScreenState }) {
  const [screen, setScreen] = useState<ScreenState>(initialScreen); const [form, setForm] = useState<LifelineFormData>(EMPTY_FORM); const [result, setResult] = useState<LifelineResult | null>(null); const [error, setError] = useState(""); const [loadStep, setLoadStep] = useState(0); const resultsRef = useRef<HTMLElement>(null);
  useEffect(() => { if (screen !== "loading") { setLoadStep(0); return; } const first = window.setTimeout(() => setLoadStep(1), 1400); const second = window.setTimeout(() => setLoadStep(2), 3000); return () => { window.clearTimeout(first); window.clearTimeout(second); }; }, [screen]);
  useEffect(() => { if (screen === "results") resultsRef.current?.scrollIntoView({ behavior: "smooth" }); }, [screen]);
  const updateForm = (key: keyof LifelineFormData, value: string) => { setForm((current) => ({ ...current, [key]: value })); if (error) setError(""); };
  const handleCityChange = (city: string) => { const state = detectState(city); setForm((current) => ({ ...current, city, state: state || current.state })); if (error) setError(""); };
  const handleReset = () => { setScreen("intro"); setForm(EMPTY_FORM); setResult(null); setError(""); setLoadStep(0); };
  async function handleSubmit() { if (!form.crisisType) return setError("Select the situation that best describes what is happening."); if (form.description.trim().length < 20) return setError("Please share a little more detail (at least 20 characters)."); if (!form.monthlyIncome || Number(form.monthlyIncome) <= 0) return setError("Enter your monthly income to continue."); if (!form.city.trim()) return setError("Enter your city to continue."); if (!form.state) return setError("Select your state so we can find state-specific support."); if (!form.earnerType) return setError("Select your work type to continue."); setError(""); setScreen("loading"); setResult(null); try { const response = await fetch("/api/lifeline", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json() as { success?: boolean; error?: string; result?: LifelineResult }; if (data.success && data.result) { setResult(data.result); setScreen("results"); } else { setError(data.error || "We could not create your plan. Please try again."); setScreen("input"); } } catch { setError("We could not connect right now. Please check your connection and try again."); setScreen("input"); } }
  if (screen === "loading") return <main className="lifeline-loading" aria-live="polite" aria-busy="true"><div className="lifeline-loading-card"><div className="lifeline-spinner" /><p className="lifeline-kicker">Creating your recovery plan</p><h1>Finding the right next steps</h1><div className="lifeline-loading-steps"><p className="active">Reviewing your situation</p>{loadStep >= 1 && <p>Matching relevant support</p>}{loadStep >= 2 && <p>Organising a practical plan</p>}</div></div></main>;
  if (screen === "intro") return <main className="lifeline"><div className="lifeline-shell"><FlowHeader step={1} /><section className="lifeline-hero"><p className="lifeline-kicker">Crisis guidance and support discovery</p><h1>Clear next steps<br />when life feels <mark>uncertain.</mark></h1><p>Lifeline turns a difficult situation into a calm, practical plan — helping you prioritise the next few hours and identify relevant public support.</p><div className="lifeline-value-grid"><div><b>Today</b><span>Practical actions for the next 24 hours</span></div><div><b>Support</b><span>National and state programme routes</span></div><div><b>Clarity</b><span>One priority to focus on right now</span></div></div><button className="lifeline-primary slim" onClick={() => setScreen("input")}>Build my Lifeline plan <span>→</span></button><p className="lifeline-trust">Private by design · No account required · Free to use</p></section><section className="lifeline-how"><div className="lifeline-section-heading"><span className="lifeline-section-marker" /><div><h2>How Lifeline works</h2><p>A focused assessment that takes about two minutes.</p></div></div>{[["01", "Choose the situation", "Select the issue that needs attention first."], ["02", "Add your city and state", "We use your location to find local support routes."], ["03", "Get a recovery plan", "See national and state programmes to verify."]].map(([number, title, copy]) => <div className="lifeline-step" key={number}><b>{number}</b><p><strong>{title}</strong><span>{copy}</span></p></div>)}</section></div></main>;
  if (screen === "input") return <main className="lifeline"><div className="lifeline-shell lifeline-form"><header><FlowHeader step={2} /><button className="lifeline-back" onClick={handleReset}>← Overview</button></header><div className="lifeline-form-intro"><p className="lifeline-kicker">Step 2 of 3 · Your situation</p><h1>Tell us what needs attention.</h1><p>Your answers help us organise the most relevant guidance and support options.</p></div><fieldset><legend>What is happening right now?</legend><div className="lifeline-crisis-list">{CRISIS_TYPES.map((crisis) => <button type="button" className={`lifeline-crisis ${form.crisisType === crisis.value ? "selected" : ""}`} onClick={() => updateForm("crisisType", crisis.value)} key={crisis.value}><span>{crisis.emoji}</span><div><strong>{crisis.title}</strong><small>{crisis.description}</small></div><b>{form.crisisType === crisis.value ? "Selected" : "Select"}</b></button>)}</div></fieldset><fieldset className="lifeline-details"><legend>Help us understand your circumstances</legend><label className="lifeline-field">What happened?<textarea rows={4} value={form.description} onChange={(event) => updateForm("description", event.target.value)} placeholder="A few sentences about your situation is enough." /></label><p className={`lifeline-count ${form.description.length < 20 ? "short" : ""}`}>{form.description.length < 20 ? `${form.description.length} of 20 characters minimum` : "Enough detail provided"}</p><div className="lifeline-grid"><label>Monthly income (₹)<input type="number" min="0" inputMode="numeric" value={form.monthlyIncome} onChange={(event) => updateForm("monthlyIncome", event.target.value)} placeholder="e.g. 25,000" /></label><label>Your city<input value={form.city} onChange={(event) => handleCityChange(event.target.value)} placeholder="e.g. Bengaluru" /></label><label>State {form.city && form.state && <span className="lifeline-autodetected">Auto-detected</span>}<select value={form.state} onChange={(event) => updateForm("state", event.target.value)}><option value="">Select state</option>{STATES.map((state) => <option key={state}>{state}</option>)}</select></label><label>Family members supported <span>(optional)</span><input type="number" min="0" inputMode="numeric" value={form.familySize} onChange={(event) => updateForm("familySize", event.target.value)} placeholder="e.g. 4" /></label><label className="lifeline-grid-wide">Work type<select value={form.earnerType} onChange={(event) => updateForm("earnerType", event.target.value)}><option value="">Select your type</option>{EARNER_TYPES.map((type) => <option key={type}>{type}</option>)}</select></label></div></fieldset>{error && <p className="lifeline-error" role="alert">{error}</p>}<button className="lifeline-primary" onClick={handleSubmit}>Create my recovery plan <span>→</span></button><p className="lifeline-trust">Your details are used only to prepare this plan.</p></div></main>;
  if (!result) return null;
  const urgency = result.urgencyLevel === "critical" ? "Urgent support recommended" : result.urgencyLevel === "high" ? "High-priority plan" : "Your Lifeline plan"; const schemeCount = result.nationalSchemes.length + result.stateSchemes.length;
  return <main className="lifeline lifeline-results" ref={resultsRef}><div className={`lifeline-urgency ${result.urgencyLevel}`}><span className="lifeline-urgency-dot" />{urgency}<button onClick={() => setScreen("input")}>Edit details</button></div><div className="lifeline-shell"><FlowHeader step={3} /><section className="lifeline-opening"><small>Your personalised plan</small><h1>Here&apos;s where to begin.</h1><p>{result.openingMessage}</p></section><section className="lifeline-now"><small>Priority for the next 30 minutes</small><p>{result.oneActionNow}</p></section><section className="lifeline-total"><small>Support routes identified</small><strong>{schemeCount}</strong><p>national and {result.stateName} programmes to check</p><em>No combined cash estimate is shown: final benefits depend on the programme’s eligibility check.</em></section><Actions title="Next 24 hours" subtitle="Stabilise the essentials first." items={result.next24Hours} tone="urgent" /><Actions title="This week" subtitle="Build a little breathing room." items={result.thisWeek} tone="week" /><Actions title="This month" subtitle="Set up your recovery path." items={result.thisMonth} tone="month" /><SchemeGroup type="national" stateName={result.stateName} schemes={result.nationalSchemes} /><div className="lifeline-scheme-divider">AND</div><SchemeGroup type="state" stateName={result.stateName} schemes={result.stateSchemes} /><section className="lifeline-donot"><div className="lifeline-section-heading"><span className="lifeline-section-marker" /><div><h2>Things to avoid for now</h2><p>These can make a difficult situation harder.</p></div></div>{result.doNotDo.map((item, index) => <p key={`${item}-${index}`}><span>{String(index + 1).padStart(2, "0")}</span>{item}</p>)}</section><section className="lifeline-helplines"><div className="lifeline-section-heading"><span className="lifeline-section-marker" /><div><h2>Useful helplines</h2><p>Use these if you need support now.</p></div></div><div>{result.helplines.map((helpline) => <article key={`${helpline.name}-${helpline.number}`}><small>{helpline.available}</small><strong>{helpline.name}</strong><b>{helpline.number}</b><em>{helpline.useFor}</em></article>)}</div></section><div className="lifeline-bottom"><button className="lifeline-secondary" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}>Back to plan overview</button><button className="lifeline-ghost" onClick={handleReset}>Start a new Lifeline</button></div></div></main>;
}
